name: SVN to GitHub Migration
on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Git credentials
        run: |
          git config --global user.email "ayushsaini963@gmail.com"
          git config --global user.name "Ayushsaini20"
      - name: Install JFrog CLI
        run: |
          curl -fL https://getcli.jfrog.io | sh
          sudo mv jfrog /usr/local/bin/jfrog
      - name: Ensure SVN directory structure and permissions
        run: |
          mkdir -p svn_repo/.svn/tmp
          sudo chmod -R 777 svn_repo/.svn/tmp
      - name: Clean up any previous SVN checkout
        run: |
          rm -rf svn_repo
      - name: Clone SVN repository
        run: |

      - name: Extract JFrog Artifactory URLs for binary files
        run: |
          find . -type f \( -name "*.exe" -o -name "*.dll" -o -name "*.bin" \) | while read binary; do
            binary_name=$(basename "$binary")
            jfrog_url="https://ayushsaini.jfrog.io/artifactory/demo-generic-local/$binary_name"

      - name: Upload binaries to JFrog Artifactory
        run: |
          find . -type f \( -name "*.exe" -o -name "*.dll" -o -name "*.bin" \) | while read binary; do
            binary_name=$(basename "$binary")
            curl -u "ayush.sai@statusneo.com:CSWC++@sa2023" --upload-file "$binary" "https://ayushsaini.jfrog.io/artifactory/demo-generic-local/$binary_name" || { echo "Failed to upload $binary to JFrog"; exit 1; }
          done
      - name: Commit and push to GitHub
        run: |
          # Add all files excluding binaries
          find . -type f \( ! -iname "*.exe" -a ! -iname "*.dll" -a ! -iname "*.bin" \) -exec git add {} +
          
          # Commit URL pointers back to Git instead of binaries
          git commit -m "Initial commit with binaries moved to JFrog"
          
          # Add GitHub repository as remote
          git remote add github_repo https://github.com/Ayushsaini20/svn2git.git
          # Push to GitHub
          git config --global credential.helper store
          git config --global user.email "$GIT_EMAIL"
          git config --global user.name "$GIT_NAME"
          echo "https://Ayushsaini20:${{secrets.PAT}}@github.com/Ayushsaini20/svn2git.git" > ~/.git-credentials
          git push --all github_repo
          git push --tags github_repo
